import assert from "node:assert/strict";

globalThis.localStorage={values:new Map(),getItem(key){return this.values.get(key)??null},setItem(key,value){this.values.set(key,value)},removeItem(key){this.values.delete(key)},clear(){this.values.clear()}};
globalThis.document={activeElement:null,addEventListener(){},querySelector(){return null},querySelectorAll(){return[]}};
globalThis.window={};
const {gameState,createGameState}=await import("../js/state.js");
const {createNewGame,acknowledgeOpening,launchExternalGame,consumeExternalGameResult,abandonPendingExternalGame,recoverIncompleteLaunch,resumePendingExternalGame,clearInvalidIntegrationTransaction}=await import("../js/game.js");
const {ACTIVE_GAME_KEY,GAME_RESULT_KEY,loadActiveGame,loadGameResult,classifyIntegrationState}=await import("../js/integration-host.js");
const {loadSession,restoreSession,saveSession}=await import("../js/session-persistence.js");
const {getEffectiveGameStaminaCost}=await import("../js/events.js");

const resetRun=(randomFn=()=>0)=>{createNewGame({name:"阿夜"},randomFn);acknowledgeOpening();gameState.session.presentation=null;gameState.session.presentationQueue=[];gameState.session.pendingIncident=null;return gameState.stalls.find(stall=>stall.id==="game_01")};
const resultFor=(overrides={})=>{const active=loadActiveGame().value;return{version:1,resultId:`result-${active.actionId}`,sessionId:active.sessionId,actionId:active.actionId,gameId:active.gameId,stallId:active.stallId,baseMoneyReward:100,termination:"completed",nextAction:"return",details:{fixture:true},createdAt:"2026-09-05T02:00:00.000Z",...overrides}};
const storeResult=overrides=>{const result=resultFor(overrides);localStorage.setItem(GAME_RESULT_KEY,JSON.stringify(result));return result};
const gameplaySnapshot=()=>({stamina:gameState.player.stamina,money:gameState.player.money,pending:structuredClone(gameState.session.pendingExternalGame),consumed:gameState.session.lastConsumedResultId,life:gameState.stalls[0].life,progress:gameState.progress.gameActionCount,statistics:structuredClone(gameState.statistics),achievements:gameState.achievements.map(item=>item.unlocked),incident:structuredClone(gameState.session.pendingIncident)});

let stall=resetRun();Object.assign(gameState.environment,{crowdLevel:5,temperatureLevel:5});const beforeStamina=gameState.player.stamina,cost=getEffectiveGameStaminaCost(stall,gameState.environment);
const launch=launchExternalGame("game_01",{createActionIdFn:()=>"action-launch",now:()=>new Date("2026-09-05T01:00:00.000Z")});
assert.deepEqual({ok:launch.ok,status:launch.status,cost:launch.staminaCost},{ok:true,status:"launch_ready",cost});assert.equal(gameState.player.stamina,beforeStamina-cost);
assert.equal(gameState.session.pendingExternalGame.actionId,launch.actionId);assert.deepEqual(loadSession().capsule.pendingExternalGame,gameState.session.pendingExternalGame);
const active=loadActiveGame().value;assert.equal(active.actionId,launch.actionId);assert.equal(active.sessionId,gameState.session.integrationSessionId);assert.equal(active.gameId,"NML_MoMaJohn");assert.equal(active.stallId,"game_01");assert.equal(active.player.name,"阿夜");

for(const configure of [
  ()=>{gameState.player.stamina=0},()=>{stall.isClosed=true},()=>{stall.isBlocked=true},()=>{stall.life=0},()=>{gameState.session.pendingExternalGame={}},
]){stall=resetRun();configure();const before=gameplaySnapshot();const failed=launchExternalGame("game_01");assert.equal(failed.ok,false);assert.deepEqual(gameplaySnapshot(),before);assert.equal(loadActiveGame().status,"empty")}
stall=resetRun();const unsupportedBefore=gameplaySnapshot();assert.equal(launchExternalGame("game_02").ok,false);assert.deepEqual(gameplaySnapshot(),unsupportedBefore);
stall=resetRun();localStorage.setItem(GAME_RESULT_KEY,"{}");const unresolvedBefore=gameplaySnapshot();assert.equal(launchExternalGame("game_01").reason,"unresolved_transport");assert.deepEqual(gameplaySnapshot(),unresolvedBefore);localStorage.removeItem(GAME_RESULT_KEY);

stall=resetRun();const sessionFailureBefore=gameplaySnapshot();const sessionFailure=launchExternalGame("game_01",{saveSessionFn:()=>({ok:false,error:new Error("quota")})});assert.equal(sessionFailure.status,"session_save_failed");assert.deepEqual(gameplaySnapshot(),sessionFailureBefore);assert.equal(loadActiveGame().status,"empty");
stall=resetRun();let saveCalls=0;const activeFailureBefore=gameplaySnapshot();const activeFailure=launchExternalGame("game_01",{saveSessionFn:state=>(saveCalls++,saveSession(state)),saveActiveGameFn:()=>({ok:false,error:new Error("quota")})});assert.equal(activeFailure.status,"active_save_failed");assert.equal(saveCalls,2);assert.deepEqual(gameplaySnapshot(),activeFailureBefore);assert.equal(loadSession().capsule.pendingExternalGame,null);
stall=resetRun();saveCalls=0;const rollbackSaveBefore=gameplaySnapshot();const rollbackSaveFailure=launchExternalGame("game_01",{saveSessionFn:state=>{saveCalls+=1;return saveCalls===1?saveSession(state):{ok:false,error:new Error("rollback quota")}},saveActiveGameFn:()=>({ok:false,error:new Error("active quota")})});assert.equal(rollbackSaveFailure.status,"rollback_save_failed");assert.deepEqual(gameplaySnapshot(),rollbackSaveBefore);assert.notEqual(loadSession().capsule.pendingExternalGame,null);localStorage.removeItem(ACTIVE_GAME_KEY);

for(const termination of ["completed","user_exit"]){for(const reward of [100,0,-100]){stall=resetRun();gameState.player.money=500;const life=stall.life,actions=gameState.progress.gameActionCount;launchExternalGame("game_01");const result=storeResult({termination,baseMoneyReward:reward});const consumed=consumeExternalGameResult();assert.equal(consumed.status,"consumed");assert.equal(gameState.player.money,500+reward);assert.equal(gameState.statistics.stallMoneyFlow.game_01,reward);assert.equal(stall.life,life-1);assert.equal(gameState.progress.gameActionCount,actions+1);assert.equal(gameState.statistics.gamePlays.game_01,1);assert.equal(gameState.statistics.stallVisits.game_01,1);assert.equal(gameState.session.lastConsumedResultId,result.resultId);assert.equal(gameState.session.pendingExternalGame,null);assert.equal(loadActiveGame().status,"empty");assert.equal(loadGameResult().status,"empty")}}

for(const [level,expected] of [[1,80],[3,100],[5,150]]){stall=resetRun();gameState.environment.rewardLevel=level;gameState.player.money=500;launchExternalGame("game_01");storeResult({baseMoneyReward:100});const consumed=consumeExternalGameResult();assert.equal(consumed.actualMoneyReward,expected);assert.equal(gameState.player.money,500+expected);assert.equal(gameState.statistics.stallMoneyFlow.game_01,expected)}
stall=resetRun();gameState.player.money=30;launchExternalGame("game_01");storeResult({baseMoneyReward:-100});const clamped=consumeExternalGameResult();assert.equal(clamped.actualMoneyReward,-100);assert.equal(clamped.appliedMoneyReward,-30);assert.equal(gameState.player.money,0);assert.equal(gameState.statistics.stallMoneyFlow.game_01,-30);

stall=resetRun();gameState.progress.nextIncidentAt=1;launchExternalGame("game_01");const incidentResult=storeResult();consumeExternalGameResult({randomFn:()=>0});assert.ok(gameState.session.pendingIncident);assert.equal(gameState.progress.gameActionCount,1);assert.equal(gameState.session.lastConsumedResultId,incidentResult.resultId);

stall=resetRun();gameState.progress.nextIncidentAt=99;for(let index=0;index<3;index+=1){launchExternalGame("game_01");storeResult({resultId:`achievement-${index}`});consumeExternalGameResult()}assert.equal(gameState.statistics.gamePlays.game_01,3);assert.equal(gameState.achievements.find(item=>item.id==="COME_ALL_THE_WAY").unlocked,true);

stall=resetRun();gameState.progress.nextIncidentAt=1;gameState.statistics.gamePlays.game_01=2;launchExternalGame("game_01");const rollbackResult=storeResult();const rollbackBefore=gameplaySnapshot();const rollback=consumeExternalGameResult({saveSessionFn:()=>({ok:false,error:new Error("quota")}),randomFn:()=>0});assert.equal(rollback.status,"session_save_failed");assert.deepEqual(gameplaySnapshot(),rollbackBefore);assert.equal(loadActiveGame().status,"valid");assert.equal(loadGameResult().value.resultId,rollbackResult.resultId);assert.equal(gameState.achievements.find(item=>item.id==="COME_ALL_THE_WAY").unlocked,false);assert.equal(gameState.session.pendingIncident,null);

stall=resetRun();const retrySession=gameState.session.integrationSessionId,retryFirst=launchExternalGame("game_01"),retryCost=retryFirst.staminaCost;storeResult({nextAction:"retry"});assert.equal(consumeExternalGameResult().nextAction,"retry");const staminaBeforeRetry=gameState.player.stamina,retrySecond=launchExternalGame("game_01");assert.ok(retrySecond.ok);assert.equal(gameState.session.integrationSessionId,retrySession);assert.notEqual(retrySecond.actionId,retryFirst.actionId);assert.equal(gameState.player.stamina,staminaBeforeRetry-retryCost);

stall=resetRun();const pendingLaunch=launchExternalGame("game_01"),pendingBefore=gameplaySnapshot(),activeBefore=loadActiveGame().value;let navigated=null;const resumed=resumePendingExternalGame({navigateFn:url=>navigated=url});assert.equal(resumed.actionId,activeBefore.actionId);assert.equal(resumed.sessionId,activeBefore.sessionId);assert.equal(navigated,"/NML_MoMaJohn/?context=nightMarket");assert.deepEqual(gameplaySnapshot(),pendingBefore);
const abandonBefore=gameplaySnapshot(),abandoned=abandonPendingExternalGame();assert.equal(abandoned.status,"abandoned");assert.equal(gameState.player.stamina,abandonBefore.stamina);assert.equal(gameState.player.money,abandonBefore.money);assert.equal(gameState.stalls[0].life,abandonBefore.life);assert.equal(gameState.progress.gameActionCount,abandonBefore.progress);assert.equal(gameState.session.pendingExternalGame,null);assert.equal(loadActiveGame().status,"empty");
stall=resetRun();launchExternalGame("game_01");const abandonFailureBefore=gameplaySnapshot();const abandonFailure=abandonPendingExternalGame({saveSessionFn:()=>({ok:false})});assert.equal(abandonFailure.status,"session_save_failed");assert.deepEqual(gameplaySnapshot(),abandonFailureBefore);assert.equal(loadActiveGame().status,"valid");

stall=resetRun();const fullStamina=gameState.player.stamina;launchExternalGame("game_01");localStorage.removeItem(ACTIVE_GAME_KEY);const deducted=gameState.player.stamina,pendingIdentity=structuredClone(gameState.session.pendingExternalGame);const recoveredIncomplete=recoverIncompleteLaunch();assert.equal(recoveredIncomplete.status,"incomplete_recovered");assert.equal(gameState.player.stamina,fullStamina);assert.equal(gameState.session.pendingExternalGame,null);assert.equal(recoverIncompleteLaunch().status,"idle");assert.equal(gameState.player.stamina,fullStamina);
stall=resetRun();launchExternalGame("game_01");localStorage.removeItem(ACTIVE_GAME_KEY);const incompleteFailureBefore=gameplaySnapshot();const incompleteFailure=recoverIncompleteLaunch({saveSessionFn:()=>({ok:false})});assert.equal(incompleteFailure.status,"session_save_failed");assert.deepEqual(gameplaySnapshot(),incompleteFailureBefore);assert.equal(gameState.player.stamina,incompleteFailureBefore.stamina);assert.deepEqual(gameState.session.pendingExternalGame,incompleteFailureBefore.pending);

stall=resetRun();launchExternalGame("game_01");let staleActive=loadActiveGame().value;staleActive={...staleActive,actionId:"stale-action"};localStorage.setItem(ACTIVE_GAME_KEY,JSON.stringify(staleActive));let invalidBefore=gameplaySnapshot();let invalidCleanup=clearInvalidIntegrationTransaction();assert.equal(invalidCleanup.status,"invalid_transport_cleared");assert.equal(gameState.player.stamina,invalidBefore.stamina);assert.equal(gameState.session.pendingExternalGame,null);assert.equal(loadActiveGame().status,"empty");assert.equal(loadGameResult().status,"empty");assert.equal(classifyIntegrationState({session:gameState.session}),"IDLE");
stall=resetRun();launchExternalGame("game_01");localStorage.setItem(ACTIVE_GAME_KEY,"{");localStorage.setItem(GAME_RESULT_KEY,"{");invalidBefore=gameplaySnapshot();invalidCleanup=clearInvalidIntegrationTransaction();assert.equal(invalidCleanup.ok,true);assert.equal(gameState.player.stamina,invalidBefore.stamina);assert.equal(gameState.session.pendingExternalGame,null);assert.equal(loadActiveGame().status,"empty");assert.equal(loadGameResult().status,"empty");
stall=resetRun();launchExternalGame("game_01");localStorage.setItem(ACTIVE_GAME_KEY,"{");localStorage.setItem(GAME_RESULT_KEY,"{");invalidBefore=gameplaySnapshot();const activeRaw=localStorage.getItem(ACTIVE_GAME_KEY),resultRaw=localStorage.getItem(GAME_RESULT_KEY),invalidFailure=clearInvalidIntegrationTransaction({saveSessionFn:()=>({ok:false})});assert.equal(invalidFailure.status,"session_save_failed");assert.deepEqual(gameplaySnapshot(),invalidBefore);assert.equal(localStorage.getItem(ACTIVE_GAME_KEY),activeRaw);assert.equal(localStorage.getItem(GAME_RESULT_KEY),resultRaw);

stall=resetRun();launchExternalGame("game_01");const onceResult=storeResult();const keep=()=>({ok:true});const first=consumeExternalGameResult({clearActiveGameFn:keep,clearGameResultFn:keep});assert.equal(first.status,"consumed");const afterFirst=gameplaySnapshot();assert.equal(classifyIntegrationState({session:gameState.session,activeGame:loadActiveGame().value,gameResult:loadGameResult().value}),"RESULT_ALREADY_CONSUMED");const second=consumeExternalGameResult();assert.equal(second.status,"already_consumed");assert.deepEqual(gameplaySnapshot(),afterFirst);assert.equal(loadActiveGame().status,"empty");assert.equal(loadGameResult().status,"empty");

const loaded=loadSession(),restored=createGameState();assert.equal(restoreSession(restored,loaded.capsule,{}),true);assert.deepEqual({money:restored.player.money,stamina:restored.player.stamina,life:restored.stalls[0].life,actions:restored.progress.gameActionCount,statistics:restored.statistics,consumed:restored.session.lastConsumedResultId,pending:restored.session.pendingExternalGame},{money:gameState.player.money,stamina:gameState.player.stamina,life:gameState.stalls[0].life,actions:gameState.progress.gameActionCount,statistics:gameState.statistics,consumed:onceResult.resultId,pending:null});

for(const mutate of [value=>value.sessionId="old-session",value=>value.actionId="old-action",value=>value.gameId="unknown",value=>value.stallId="game_02"]){stall=resetRun();launchExternalGame("game_01");const bad=storeResult();mutate(bad);localStorage.setItem(GAME_RESULT_KEY,JSON.stringify(bad));const before=gameplaySnapshot(),attempt=consumeExternalGameResult();assert.equal(attempt.ok,false);assert.deepEqual(gameplaySnapshot(),before)}
stall=resetRun();launchExternalGame("game_01");localStorage.setItem(GAME_RESULT_KEY,"{");let before=gameplaySnapshot();assert.equal(consumeExternalGameResult().status,"corrupt");assert.deepEqual(gameplaySnapshot(),before);
localStorage.setItem(GAME_RESULT_KEY,JSON.stringify(resultFor()));localStorage.setItem(ACTIVE_GAME_KEY,"{");before=gameplaySnapshot();assert.equal(consumeExternalGameResult().status,"corrupt");assert.deepEqual(gameplaySnapshot(),before);
console.log("NightMarketLife integration transaction tests: PASS");
