import assert from "node:assert/strict";
globalThis.localStorage={values:new Map(),getItem(k){return this.values.get(k)??null},setItem(k,v){this.values.set(k,v)},removeItem(k){this.values.delete(k)}};
const {createGameState}=await import("../js/state.js");
const {RUN_SESSION_KEY,SESSION_VERSION,createSessionId,buildSessionCapsule,validateSessionCapsule,saveSession,loadSession,restoreSession,clearSession}=await import("../js/session-persistence.js");
const {saveCharacterSettings,loadCharacterSettings}=await import("../js/storage.js");
const state=createGameState({name:"阿夜",buildId:"college",avatar:"data:image/png;base64,x"});state.session.integrationSessionId=createSessionId();state.session.nightConditionId="ANNIVERSARY";state.session.startingMoney=800;state.session.scene="NIGHT_MARKET";
state.player.stamina=61;state.player.money=945;Object.assign(state.environment,{crowdLevel:4,priceLevel:2,rewardLevel:4,temperatureLevel:3,businessLevel:5});
Object.assign(state.stalls[0],{life:0,isClosed:true,isBlocked:false});Object.assign(state.stalls[1],{life:3,isClosed:false,isBlocked:true});state.progress={gameActionCount:3,nextIncidentAt:5};state.statistics.gamePlays={game_01:3};state.statistics.stallVisits={game_01:3};state.statistics.stallMoneyFlow={game_01:145};state.statistics.incidentHistory=[{eventId:"PRICE_DOWN",gameActionCount:2,details:{key:"priceLevel",before:3,after:2}}];state.achievements[0].unlocked=true;state.session.achievementTracking.staminaZero=true;state.session.presentation={type:"ACTIVITY_RESULT"};state.session.presentationQueue=[{type:"RESOURCE_WARNING_MODAL"}];
const id1=state.session.integrationSessionId,id2=createSessionId();assert.notEqual(id1,id2);assert.ok(id1.length>=8);
const capsule=buildSessionCapsule(state,()=>new Date("2026-09-04T00:00:00Z"));assert.equal(capsule.version,SESSION_VERSION);assert.equal(capsule.pendingExternalGame,null);assert.equal(capsule.lastConsumedResultId,null);assert.equal(Object.hasOwn(capsule,"presentation"),false);assert.equal(Object.hasOwn(capsule,"presentationQueue"),false);assert.ok(validateSessionCapsule(capsule));
assert.equal(saveSession(state).ok,true);assert.equal(loadSession().status,"valid");assert.equal(localStorage.values.has(RUN_SESSION_KEY),true);
const target=createGameState({avatar:"data:image/png;base64,persist"});assert.equal(restoreSession(target,loadSession().capsule,{avatar:"data:image/png;base64,persist"}),true);assert.equal(target.session.integrationSessionId,id1);assert.deepEqual([target.player.stamina,target.player.money,target.player.buildId],[61,945,"college"]);assert.equal(target.player.profile.avatar,"data:image/png;base64,persist");assert.equal(target.session.nightConditionId,"ANNIVERSARY");assert.deepEqual(target.environment,state.environment);assert.deepEqual(target.progress,state.progress);assert.deepEqual(target.statistics,state.statistics);assert.deepEqual(target.stalls.map(s=>[s.id,s.life,s.isClosed,s.isBlocked]),state.stalls.map(s=>[s.id,s.life,s.isClosed,s.isBlocked]));assert.equal(target.achievements[0].unlocked,true);assert.equal(target.session.achievementTracking.staminaZero,true);assert.equal(target.session.presentation,null);assert.deepEqual(target.session.presentationQueue,[]);
saveCharacterSettings({name:"長期玩家",buildId:"worker",avatar:"avatar"});const characterBefore=localStorage.getItem("nightMarketLife.characterSettings.v1");saveSession(state);assert.equal(localStorage.getItem("nightMarketLife.characterSettings.v1"),characterBefore);assert.equal(loadCharacterSettings().name,"長期玩家");
for(const mutate of [c=>c.version=2,c=>c.player.money=NaN,c=>c.environment.priceLevel=6,c=>c.stalls[0].id="unknown",c=>c.achievements.pop(),c=>c.statistics.stallMoneyFlow.unknown=1,c=>c.pendingExternalGame={}] ){const bad=structuredClone(capsule);mutate(bad);assert.equal(validateSessionCapsule(bad),false);const untouched=JSON.stringify(target);assert.equal(restoreSession(target,bad,{}),false);assert.equal(JSON.stringify(target),untouched);}
localStorage.setItem(RUN_SESSION_KEY,"{");assert.equal(loadSession().status,"corrupt");localStorage.setItem(RUN_SESSION_KEY,JSON.stringify({...capsule,version:99}));assert.equal(loadSession().status,"corrupt");clearSession();assert.equal(loadSession().status,"empty");
console.log("NightMarketLife run session persistence tests: PASS");
