const assert=require('node:assert/strict');const{chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage({viewport:{width:390,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.goto(process.env.NML_TEST_URL||'http://127.0.0.1:4173/');await page.evaluate(()=>localStorage.clear());await page.reload();
await page.locator('#player-name').fill('續逛玩家');await page.getByRole('button',{name:'開始遊戲',exact:true}).click();await page.getByRole('button',{name:'開始逛夜市'}).click();
await page.evaluate(async()=>{const d=NMLDebug,s=d.getState();s.progress.nextIncidentAt=99;d.playTestGame('game_01',()=>0);(await import('/js/game.js?v=core-ui-stall-grid')).clearActivityResultPresentation();d.buyFood('food_01',()=>0);(await import('/js/game.js?v=core-ui-stall-grid')).clearActivityResultPresentation();d.closeStall('game_03');s.stalls.find(x=>x.id==='game_02').isBlocked=true;d.setEnvironmentLevel('temperatureLevel',5);s.achievements[0].unlocked=true;d.setEnvironmentLevel('crowdLevel',4);});
const snapshot=()=>page.evaluate(()=>{const s=NMLDebug.getState();return{sessionId:s.session.integrationSessionId,money:s.player.money,stamina:s.player.stamina,build:s.player.buildId,night:s.session.nightConditionId,environment:s.environment,stalls:s.stalls.map(x=>[x.id,x.life,x.isClosed,x.isBlocked]),progress:s.progress,statistics:s.statistics,achievements:s.achievements.map(x=>[x.id,x.unlocked]),tracking:s.session.achievementTracking}});const before=await snapshot();
await page.reload();assert.ok(await page.getByText('今晚還沒逛完').isVisible());const storedId=await page.evaluate(()=>NMLDebug.getRunSession().capsule.sessionId);await page.locator('#player-name').fill('不應覆蓋');await page.getByRole('button',{name:'開始遊戲',exact:true}).click();assert.equal(await page.evaluate(()=>NMLDebug.getRunSession().capsule.sessionId),storedId);assert.equal(await page.evaluate(()=>NMLDebug.getState().session.scene),'HOME');
await page.getByRole('button',{name:'繼續逛夜市'}).click();const after=await snapshot();assert.deepEqual(after,before);assert.equal(await page.evaluate(()=>NMLDebug.getState().session.presentation),null);
await page.locator('[data-action="go-home"]').click();await page.locator('[data-action="confirm-home"]').click();assert.ok(await page.locator('[data-scene="RESULT"]').isVisible());assert.equal((await page.evaluate(()=>NMLDebug.getRunSession())).status,'valid');
await page.getByRole('button',{name:'回首頁'}).click();await page.reload();await page.getByRole('button',{name:'放棄這一晚'}).click();assert.equal((await page.evaluate(()=>NMLDebug.getRunSession())).status,'empty');
await page.evaluate(()=>localStorage.setItem('nightMarketLife.session.active.v1','{"broken":true}'));await page.reload();assert.ok(await page.getByText('上次的夜市紀錄似乎壞掉了。').isVisible());assert.equal(await page.locator('[data-action="continue-session"]').count(),1);assert.equal(await page.locator('[data-action="continue-session"]').isVisible(),false);await page.getByRole('button',{name:'放棄這一晚'}).click();
for(const [w,h] of [[320,844],[390,844],[390,900],[430,932]]){await page.setViewportSize({width:w,height:h});await page.evaluate(()=>{localStorage.setItem('nightMarketLife.session.active.v1','bad')});await page.reload();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const panel=page.locator('[data-session-recovery]');assert.ok(await panel.isVisible());}
assert.deepEqual(errors,[]);console.log('Run session browser reload/continue/abandon/corrupt/result/responsive: PASS; console errors 0');}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
