"""Scan character asset folders and regenerate assets/character-assets.js."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets"
SUPPORTED_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp"}


def scan(relative_directory: str, label: str) -> list[dict[str, str]]:
    directory = ASSETS / relative_directory
    files = sorted(
        (path for path in directory.iterdir() if path.is_file() and path.suffix.lower() in SUPPORTED_EXTENSIONS),
        key=lambda path: path.name.casefold(),
    ) if directory.exists() else []
    return [
        {
            "id": path.stem,
            "name": f"{label} {index}",
            "src": f"assets/{relative_directory.replace(chr(92), '/')}/{path.name}",
        }
        for index, path in enumerate(files, start=1)
    ]


def js_array(name: str, records: list[dict[str, str]]) -> str:
    lines = [f"export const {name} = Object.freeze(["]
    for record in records:
        lines.append(
            f'  Object.freeze({{ id: "{record["id"]}", name: "{record["name"]}", src: "{record["src"]}" }}),'
        )
    lines.append("]);")
    return "\n".join(lines)


def main() -> None:
    faces = scan("faces", "預設臉")
    default_clothes = scan("clothes/default", "預設衣服")
    shop_clothes = scan("clothes/shop", "商店衣服")
    output = """// Generated by tools/generate-character-assets.py. Do not edit asset paths by hand.
// Future shop entries may add: price, rarity, effectId, description.

"""
    output += js_array("FACE_ASSETS", faces) + "\n\n"
    output += js_array("DEFAULT_CLOTHES", default_clothes) + "\n\n"
    output += js_array("SHOP_CLOTHES", shop_clothes) + "\n"
    (ASSETS / "character-assets.js").write_text(output, encoding="utf-8")


if __name__ == "__main__":
    main()
